### ISSUE TITLE
New Command: create-local-cluster-with-crc

### ISSUE THREAD

**Issue by wenzowski** [CircleCI-Public/redhat-openshift-orb#7]
As of OpenShift 4.1, Red Hat has migrated to a new tool for spinning up local clusters. The new solution is called [CodeReady Containers](https://code-ready.github.io/crc/#understanding-codeready-containers_gsg) and a [Developer Preview](https://cloud.redhat.com/openshift/install/crc/installer-provisioned?intcmp=7013a000002CtetAAC) is available.

**Comment by techytushar** [comment]
@lokst @wenzowski  Please can you tell what needs to be done to solve this issue, I would like to work on this

**Comment by wenzowski** [comment]
I'm hoping for a new command, like [create-local-cluster-with-oc](https://github.com/CircleCI-Public/redhat-openshift-orb/blob/master/src/commands/create-local-cluster-with-oc.yml) that creates a local cluster using`crc` in place of `oc`.

I would expect the first step would be to get the `crc` tool installed and setup according to the docs linked above. A [red hat account](https://developers.redhat.com/blog/2016/03/31/no-cost-rhel-developer-subscription-now-available/) is currently necessary to access the developer preview linked above.

Perhaps this means that a separate `install-code-ready-containers-cli` command equivalent to [install-openshift-cli](https://github.com/CircleCI-Public/redhat-openshift-orb/blob/master/src/commands/install-openshift-cli.yml) is a required step before working on this issue?

**Comment by lokst** [comment]
@wenzowski Thank you for weighing in! I have not looked much into OpenShift 4.1 yet, but what you described makes sense to me!

**Comment by jmickey** [comment]
I was looking into this recently as I have a need to launch an OS4.x cluster in CircleCI. I have access to the `crc` binary.

Unfortunately I ran into a pretty major show-stopper: CodeReady Containers requires the machine executor to support **nested virtualisation**. This is because CodeReady Containers (like minishift) attempts to launch a VM on the local machine.

This is a pretty major blocker obviously. I don't see a work around unless CircleCI supports nested virtualisation some time in the near future.

**Comment by nathanfishcircleci** [comment]
We are going to archive this orb because of little to no use.
